name: game_saves_backup
description: A linux application to backup game saves.
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  file_selector: ^1.0.1
  url_launcher: ^6.2.2
  native_context_menu: ^0.2.2+5
  uuid: ^4.0.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.1
  path: ^1.8.3
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  arb_generator: ^0.0.3
  build_runner:
  riverpod_generator: ^2.3.9
  custom_lint:
  riverpod_lint: ^2.3.7
  app_store_screenshots:
    git: 
      url: https://github.com/defuncart/app_store_screenshots
      ref: feature/desktop-window-without-device-frame

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
