name: game_saves_backup
description: An application to backup game saves.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  file_selector: ^1.0.1
  url_launcher: ^6.1.14
  native_context_menu: ^0.2.2+5
  uuid: ^3.0.6
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  arb_generator: ^0.0.3
  build_runner:
  riverpod_generator: ^2.3.2
  custom_lint:
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
